apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${app}
    group: ${group}
  name: ${app}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ${app}
        group: ${group}
    spec:
      containers:
        - name: ${app}
          image: node:16-alpine3.16
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
          imagePullPolicy: IfNotPresent
          workingDir: /website
          command: ["npm", "run", "start"]
          volumeMounts:
            - mountPath: /website
              name: website
            - mountPath: /static
              name: static
      volumes:
        - name: website
          hostPath:
            path: /data/frontend/${app}
            type: DirectoryOrCreate
        - name: static
          hostPath:
            path: /data/static/${app}
            type: DirectoryOrCreate
