apiVersion: v1
kind: ConfigMap
metadata:
  name: ${group}
  namespace: default
data:
  config.toml: |
    Module = "${group}"

    [dev]
    configType = "local"
    Watch  = true
    NoInject = ["Apollo","Etcd", "Es"]
    InjectVersion = 2
    
    
    [dev.local]
    ConfigPath = "./config/${group}.toml"
    ReloadType = "fsnotify"
    
    [test]
    configType = "nacos"
    Watch  = true
    
    [dev.nacos]
    DataId = "${app}"
    Group = "${group}"
    
    [[dev.nacos.ServerConfigs]]
    Scheme = "http"
    IpAddr = "nacos.liov.xyz"
    Port = 9000
    GrpcPort = 10000
    
    [dev.nacos.ClientConfig]
    NamespaceId = ""
    username = "nacos"
    password = "123456"
    LogLevel = "debug"
    
    [prod]
    NacosTenant = ""