FROM jybl/timezone AS tz
# Builder Image
FROM node:16.16-alpine3.16 AS compile

WORKDIR /work

ADD ./* /work

RUN npm install

RUN npm run rollup-${app}

FROM node:16.16-alpine3.16

#修改容器时区
ENV TZ=Asia/Shanghai LANG=C.UTF-8
COPY --from=tz /usr/share/zoneinfo/$TZ /usr/share/zoneinfo/$TZ
RUN echo $TZ > /etc/timezone && ln -s /usr/share/zoneinfo/$TZ /etc/localtime

WORKDIR /app

COPY --from=compile /work/dist/${output} /app

RUN npm install -g nodemon

CMD ["nodemon", "${cmd}"]