FROM jybl/timezone AS tz
FROM node:16.16-alpine3.16

#修改容器时区
ENV TZ=Asia/Shanghai LANG=C.UTF-8
COPY --from=tz /usr/share/zoneinfo/$TZ /usr/share/zoneinfo/$TZ
RUN echo $TZ > /etc/timezone && ln -s /usr/share/zoneinfo/$TZ /etc/localtime

WORKDIR /app

ADD . /app

RUN npm install

RUN npm run build

CMD ["npm","run", "start"]