FROM jybl/timezone AS tz

FROM openjdk:21-jdk-alpine

ENV TZ=Asia/Shanghai LANG=C.UTF-8
COPY --from=tz /usr/share/zoneinfo/$TZ /usr/share/zoneinfo/$TZ
RUN echo $TZ > /etc/timezone && ln -s /usr/share/zoneinfo/$TZ /etc/localtime

ADD ${cmd}.jar /app
CMD ["java", "-jar", "${cmd}.jar"]
