FROM jybl/timezone AS tz

FROM jybl/face

ENV TZ=Asia/Shanghai LANG=C.UTF-8
COPY --from=tz /usr/share/zoneinfo/$TZ /usr/share/zoneinfo/$TZ
RUN echo $TZ > /etc/timezone && ln -s /usr/share/zoneinfo/$TZ /etc/localtime

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN python3 -m pip install --upgrade pip

WORKDIR /app

ADD . /app

RUN pip3 install -r requirements.txt

CMD ["python", "${cmd}"]