FROM jybl/face

ENV TZ=Asia/Shanghai LANG=C.UTF-8
COPY ./tz/localtime /etc/localtime
COPY ./tz/timezone /etc/timezone
RUN mkdir -p /usr/share/zoneinfo/Asia && ln -s /etc/localtime /usr/share/zoneinfo/Asia/Shanghai

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN python3 -m pip install --upgrade pip

WORKDIR /app

ADD . /app

RUN pip3 install -r requirements.txt

CMD ["python", "${cmd}"]