FROM jybl/timezone AS timezone

FROM openjdk:11

ENV TZ=Asia/Shanghai LANG=C.UTF-8
COPY ./tz/localtime /etc/localtime
COPY ./tz/timezone /etc/timezone
RUN mkdir -p /usr/share/zoneinfo/Asia && ln -s /etc/localtime /usr/share/zoneinfo/Asia/Shanghai