apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ${app}
  namespace: default
spec:
  http:
    - name: ${app}
      match:
        hosts:
          - ${host}
        paths:
          - /*
      backends:
        - serviceName: ${app}
          servicePort: 80
          resolveGranularity: service
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true