apiVersion: v1
kind: Service
metadata:
  name: ${app}
  namespace: default
  labels:
    app: ${app}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: ${port}
  selector:
    app: ${app}